version: 2

sources:
  - name: austin_bikeshare
    description: "Bigquery Austin bike share dataset"
    database: bigquery-public-data  
    schema: austin_bikeshare  
    tables:
      - name: bikeshare_stations
        description: "Bike station information"
      - name: bikeshare_trips
        description: "Bike trips data"

models:
  - name: austin_bikeshare__district_stations
    description: >
      Table show number of stations per 100 thousands of population
    columns:
      - name: council_district
        description: "Distrinct number"
        tests:
          - is_council_district
      - name: station_per_capita
        description: "Number of stations per 100 thousand of population"